//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineWS.RSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RSError", Namespace="http://schemas.datacontract.org/2004/07/rs")]
    [System.SerializableAttribute()]
    public partial class RSError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayerInfoData", Namespace="http://schemas.datacontract.org/2004/07/rs")]
    [System.SerializableAttribute()]
    public partial class PayerInfoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PipelineWS.RSService.Median MedianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PipelineWS.RSService.PayerInfo> PayerInfoListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PipelineWS.RSService.RSError RSErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PipelineWS.RSService.Median Median {
            get {
                return this.MedianField;
            }
            set {
                if ((object.ReferenceEquals(this.MedianField, value) != true)) {
                    this.MedianField = value;
                    this.RaisePropertyChanged("Median");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PipelineWS.RSService.PayerInfo> PayerInfoList {
            get {
                return this.PayerInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.PayerInfoListField, value) != true)) {
                    this.PayerInfoListField = value;
                    this.RaisePropertyChanged("PayerInfoList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PipelineWS.RSService.RSError RSError {
            get {
                return this.RSErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.RSErrorField, value) != true)) {
                    this.RSErrorField = value;
                    this.RaisePropertyChanged("RSError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Median", Namespace="http://schemas.datacontract.org/2004/07/rs")]
    [System.SerializableAttribute()]
    public partial class Median : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PipelineWS.RSService.MedianData> DetailListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PipelineWS.RSService.MedianData> DetailList {
            get {
                return this.DetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailListField, value) != true)) {
                    this.DetailListField = value;
                    this.RaisePropertyChanged("DetailList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayerInfo", Namespace="services.rs.ge")]
    [System.SerializableAttribute()]
    public partial class PayerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Employer_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Employer_TinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Income_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Taxable_Total_IncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_Decl_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dec_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_Decl_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vat_PayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Income_Tax_PayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Small_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Small_Status_SdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Small_Status_EdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activity_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Small_Bussines_RevenueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodField, value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Employer_Name {
            get {
                return this.Employer_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Employer_NameField, value) != true)) {
                    this.Employer_NameField = value;
                    this.RaisePropertyChanged("Employer_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Employer_Tin {
            get {
                return this.Employer_TinField;
            }
            set {
                if ((object.ReferenceEquals(this.Employer_TinField, value) != true)) {
                    this.Employer_TinField = value;
                    this.RaisePropertyChanged("Employer_Tin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Income_Type {
            get {
                return this.Income_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Income_TypeField, value) != true)) {
                    this.Income_TypeField = value;
                    this.RaisePropertyChanged("Income_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Taxable_Total_Income {
            get {
                return this.Taxable_Total_IncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.Taxable_Total_IncomeField, value) != true)) {
                    this.Taxable_Total_IncomeField = value;
                    this.RaisePropertyChanged("Taxable_Total_Income");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Income {
            get {
                return this.IncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.IncomeField, value) != true)) {
                    this.IncomeField = value;
                    this.RaisePropertyChanged("Income");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string First_Decl_Date {
            get {
                return this.First_Decl_DateField;
            }
            set {
                if ((object.ReferenceEquals(this.First_Decl_DateField, value) != true)) {
                    this.First_Decl_DateField = value;
                    this.RaisePropertyChanged("First_Decl_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Dec_Type {
            get {
                return this.Dec_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Dec_TypeField, value) != true)) {
                    this.Dec_TypeField = value;
                    this.RaisePropertyChanged("Dec_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Last_Decl_Date {
            get {
                return this.Last_Decl_DateField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_Decl_DateField, value) != true)) {
                    this.Last_Decl_DateField = value;
                    this.RaisePropertyChanged("Last_Decl_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Vat_Payed {
            get {
                return this.Vat_PayedField;
            }
            set {
                if ((object.ReferenceEquals(this.Vat_PayedField, value) != true)) {
                    this.Vat_PayedField = value;
                    this.RaisePropertyChanged("Vat_Payed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Income_Tax_Payed {
            get {
                return this.Income_Tax_PayedField;
            }
            set {
                if ((object.ReferenceEquals(this.Income_Tax_PayedField, value) != true)) {
                    this.Income_Tax_PayedField = value;
                    this.RaisePropertyChanged("Income_Tax_Payed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Small_Status {
            get {
                return this.Small_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Small_StatusField, value) != true)) {
                    this.Small_StatusField = value;
                    this.RaisePropertyChanged("Small_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Small_Status_Sdate {
            get {
                return this.Small_Status_SdateField;
            }
            set {
                if ((object.ReferenceEquals(this.Small_Status_SdateField, value) != true)) {
                    this.Small_Status_SdateField = value;
                    this.RaisePropertyChanged("Small_Status_Sdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Small_Status_Edate {
            get {
                return this.Small_Status_EdateField;
            }
            set {
                if ((object.ReferenceEquals(this.Small_Status_EdateField, value) != true)) {
                    this.Small_Status_EdateField = value;
                    this.RaisePropertyChanged("Small_Status_Edate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Activity_Type {
            get {
                return this.Activity_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Activity_TypeField, value) != true)) {
                    this.Activity_TypeField = value;
                    this.RaisePropertyChanged("Activity_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Small_Bussines_Revenue {
            get {
                return this.Small_Bussines_RevenueField;
            }
            set {
                if ((object.ReferenceEquals(this.Small_Bussines_RevenueField, value) != true)) {
                    this.Small_Bussines_RevenueField = value;
                    this.RaisePropertyChanged("Small_Bussines_Revenue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedianData", Namespace="http://schemas.datacontract.org/2004/07/rs")]
    [System.SerializableAttribute()]
    public partial class MedianData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SumIncomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SumIncome {
            get {
                return this.SumIncomeField;
            }
            set {
                if ((this.SumIncomeField.Equals(value) != true)) {
                    this.SumIncomeField = value;
                    this.RaisePropertyChanged("SumIncome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RSService.IRSSErvice")]
    public interface IRSSErvice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSErvice/GetPayerSmsCode", ReplyAction="http://tempuri.org/IRSSErvice/GetPayerSmsCodeResponse")]
        PipelineWS.RSService.GetPayerSmsCodeResponse GetPayerSmsCode(PipelineWS.RSService.GetPayerSmsCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSErvice/GetPayerSmsCode", ReplyAction="http://tempuri.org/IRSSErvice/GetPayerSmsCodeResponse")]
        System.Threading.Tasks.Task<PipelineWS.RSService.GetPayerSmsCodeResponse> GetPayerSmsCodeAsync(PipelineWS.RSService.GetPayerSmsCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSErvice/GetPayerInfoData", ReplyAction="http://tempuri.org/IRSSErvice/GetPayerInfoDataResponse")]
        PipelineWS.RSService.GetPayerInfoDataResponse GetPayerInfoData(PipelineWS.RSService.GetPayerInfoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSErvice/GetPayerInfoData", ReplyAction="http://tempuri.org/IRSSErvice/GetPayerInfoDataResponse")]
        System.Threading.Tasks.Task<PipelineWS.RSService.GetPayerInfoDataResponse> GetPayerInfoDataAsync(PipelineWS.RSService.GetPayerInfoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSErvice/GetPayerInfoDataLocal", ReplyAction="http://tempuri.org/IRSSErvice/GetPayerInfoDataLocalResponse")]
        PipelineWS.RSService.GetPayerInfoDataLocalResponse GetPayerInfoDataLocal(PipelineWS.RSService.GetPayerInfoDataLocalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSErvice/GetPayerInfoDataLocal", ReplyAction="http://tempuri.org/IRSSErvice/GetPayerInfoDataLocalResponse")]
        System.Threading.Tasks.Task<PipelineWS.RSService.GetPayerInfoDataLocalResponse> GetPayerInfoDataLocalAsync(PipelineWS.RSService.GetPayerInfoDataLocalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSErvice/GetMedian", ReplyAction="http://tempuri.org/IRSSErvice/GetMedianResponse")]
        PipelineWS.RSService.GetMedianResponse GetMedian(PipelineWS.RSService.GetMedianRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSErvice/GetMedian", ReplyAction="http://tempuri.org/IRSSErvice/GetMedianResponse")]
        System.Threading.Tasks.Task<PipelineWS.RSService.GetMedianResponse> GetMedianAsync(PipelineWS.RSService.GetMedianRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayerSmsCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPayerSmsCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string saidCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fullname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string email;
        
        public GetPayerSmsCodeRequest() {
        }
        
        public GetPayerSmsCodeRequest(string saidCode, string fullname, string mobile, string email) {
            this.saidCode = saidCode;
            this.fullname = fullname;
            this.mobile = mobile;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayerSmsCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPayerSmsCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PipelineWS.RSService.RSError GetPayerSmsCodeResult;
        
        public GetPayerSmsCodeResponse() {
        }
        
        public GetPayerSmsCodeResponse(PipelineWS.RSService.RSError GetPayerSmsCodeResult) {
            this.GetPayerSmsCodeResult = GetPayerSmsCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayerInfoData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPayerInfoDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string saidCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string smsCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int applicationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int userId;
        
        public GetPayerInfoDataRequest() {
        }
        
        public GetPayerInfoDataRequest(string saidCode, string smsCode, int applicationId, int userId) {
            this.saidCode = saidCode;
            this.smsCode = smsCode;
            this.applicationId = applicationId;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayerInfoDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPayerInfoDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PipelineWS.RSService.PayerInfoData GetPayerInfoDataResult;
        
        public GetPayerInfoDataResponse() {
        }
        
        public GetPayerInfoDataResponse(PipelineWS.RSService.PayerInfoData GetPayerInfoDataResult) {
            this.GetPayerInfoDataResult = GetPayerInfoDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayerInfoDataLocal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPayerInfoDataLocalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string saidCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int applicationId;
        
        public GetPayerInfoDataLocalRequest() {
        }
        
        public GetPayerInfoDataLocalRequest(string saidCode, int applicationId) {
            this.saidCode = saidCode;
            this.applicationId = applicationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayerInfoDataLocalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPayerInfoDataLocalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PipelineWS.RSService.PayerInfoData GetPayerInfoDataLocalResult;
        
        public GetPayerInfoDataLocalResponse() {
        }
        
        public GetPayerInfoDataLocalResponse(PipelineWS.RSService.PayerInfoData GetPayerInfoDataLocalResult) {
            this.GetPayerInfoDataLocalResult = GetPayerInfoDataLocalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMedian", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMedianRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string saidCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int applicationId;
        
        public GetMedianRequest() {
        }
        
        public GetMedianRequest(string saidCode, int applicationId) {
            this.saidCode = saidCode;
            this.applicationId = applicationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMedianResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMedianResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PipelineWS.RSService.Median GetMedianResult;
        
        public GetMedianResponse() {
        }
        
        public GetMedianResponse(PipelineWS.RSService.Median GetMedianResult) {
            this.GetMedianResult = GetMedianResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRSSErviceChannel : PipelineWS.RSService.IRSSErvice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RSSErviceClient : System.ServiceModel.ClientBase<PipelineWS.RSService.IRSSErvice>, PipelineWS.RSService.IRSSErvice {
        
        public RSSErviceClient() {
        }
        
        public RSSErviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RSSErviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RSSErviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RSSErviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PipelineWS.RSService.GetPayerSmsCodeResponse GetPayerSmsCode(PipelineWS.RSService.GetPayerSmsCodeRequest request) {
            return base.Channel.GetPayerSmsCode(request);
        }
        
        public System.Threading.Tasks.Task<PipelineWS.RSService.GetPayerSmsCodeResponse> GetPayerSmsCodeAsync(PipelineWS.RSService.GetPayerSmsCodeRequest request) {
            return base.Channel.GetPayerSmsCodeAsync(request);
        }
        
        public PipelineWS.RSService.GetPayerInfoDataResponse GetPayerInfoData(PipelineWS.RSService.GetPayerInfoDataRequest request) {
            return base.Channel.GetPayerInfoData(request);
        }
        
        public System.Threading.Tasks.Task<PipelineWS.RSService.GetPayerInfoDataResponse> GetPayerInfoDataAsync(PipelineWS.RSService.GetPayerInfoDataRequest request) {
            return base.Channel.GetPayerInfoDataAsync(request);
        }
        
        public PipelineWS.RSService.GetPayerInfoDataLocalResponse GetPayerInfoDataLocal(PipelineWS.RSService.GetPayerInfoDataLocalRequest request) {
            return base.Channel.GetPayerInfoDataLocal(request);
        }
        
        public System.Threading.Tasks.Task<PipelineWS.RSService.GetPayerInfoDataLocalResponse> GetPayerInfoDataLocalAsync(PipelineWS.RSService.GetPayerInfoDataLocalRequest request) {
            return base.Channel.GetPayerInfoDataLocalAsync(request);
        }
        
        public PipelineWS.RSService.GetMedianResponse GetMedian(PipelineWS.RSService.GetMedianRequest request) {
            return base.Channel.GetMedian(request);
        }
        
        public System.Threading.Tasks.Task<PipelineWS.RSService.GetMedianResponse> GetMedianAsync(PipelineWS.RSService.GetMedianRequest request) {
            return base.Channel.GetMedianAsync(request);
        }
    }
}
